
export default {
	INIT_TODO: 'INIT_TODO',
	ADD_TODO: 'ADD_TODO',
	UPDATE_TODO: 'UPDATE_TODO',
	DELETE_TODO: 'DELETE_TODO',
	CLEAR_COMPLETED: 'CLEAR_COMPLETED',
	SWITCH_THEME: 'SWITCH_THEME'
}